#[macro_export]
macro_rules! git_commands {
    (@commands $callback:ident [ $($acc:tt)* ]) => {
        $callback!([ $($acc)*
            // Git commands - status module
            $crate::git::status::git_is_repo,
            $crate::git::status::git_init,
            $crate::git::status::git_root,
            $crate::git::status::git_status,
            $crate::git::status::git_branches,
            $crate::git::status::git_remotes,
            $crate::git::status::git_remote,
            $crate::git::status::git_branch,
            $crate::git::status::git_head,
            // Git staging commands
            $crate::git::staging::git_stage,
            $crate::git::staging::git_unstage,
            $crate::git::staging::git_stage_all,
            $crate::git::staging::git_unstage_all,
            $crate::git::staging::git_commit,
            $crate::git::staging::git_is_gpg_configured,
            $crate::git::staging::git_discard,
            // Git diff commands
            $crate::git::diff::git_diff,
            $crate::git::diff::git_diff_staged,
            $crate::git::diff::git_diff_word_level,
            $crate::git::diff::git_diff_hunks,
            $crate::git::diff::git_diff_between_commits,
            // Git log commands
            $crate::git::log::git_log,
            $crate::git::log::git_get_refs,
            $crate::git::log::git_compare_branches,
            $crate::git::log::git_compare_commits,
            $crate::git::log::git_commit_graph,
            $crate::git::log::git_log_graph,
            // Git graph commands
            $crate::git::graph::git_get_commit_graph,
            $crate::git::log::git_get_commit_details,
            // Git stash commands
            $crate::git::stash::git_stashes,
            $crate::git::stash::git_stash_list,
            $crate::git::stash::git_stash_create,
            $crate::git::stash::git_stash_apply,
            $crate::git::stash::git_stash_pop,
            $crate::git::stash::git_stash_drop,
            $crate::git::stash::git_stash_show,
            // Git blame commands
            $crate::git::blame::git_blame,
            $crate::git::blame::git_blame_line_range,
            $crate::git::blame::git_blame_with_heatmap,
            // Git hunk staging commands
            $crate::git::hunk::git_stage_hunk,
            $crate::git::hunk::git_unstage_hunk,
            $crate::git::hunk::git_revert_hunk,
            $crate::git::hunk::git_get_hunks,
            $crate::git::hunk::git_hunk_navigate,
            // Git bisect commands
            $crate::git::bisect::git_bisect_status,
            $crate::git::bisect::git_bisect_start,
            $crate::git::bisect::git_bisect_mark,
            $crate::git::bisect::git_bisect_reset,
            // Git cherry-pick commands
            $crate::git::cherry_pick::git_commit_files,
            $crate::git::cherry_pick::git_cherry_pick,
            $crate::git::cherry_pick::git_cherry_pick_status,
            $crate::git::cherry_pick::git_cherry_pick_start,
            $crate::git::cherry_pick::git_cherry_pick_continue,
            $crate::git::cherry_pick::git_cherry_pick_skip,
            $crate::git::cherry_pick::git_cherry_pick_abort,
            // Git rebase commands
            $crate::git::rebase::git_rebase,
            $crate::git::rebase::git_rebase_commits,
            $crate::git::rebase::git_rebase_status,
            $crate::git::rebase::git_rebase_start,
            $crate::git::rebase::git_rebase_continue,
            $crate::git::rebase::git_rebase_skip,
            $crate::git::rebase::git_rebase_abort,
            $crate::git::rebase::git_rebase_todo,
            // Git submodule commands
            $crate::git::submodule::git_submodule_list,
            $crate::git::submodule::git_submodule_init,
            $crate::git::submodule::git_submodule_update,
            $crate::git::submodule::git_submodule_add,
            $crate::git::submodule::git_submodule_sync,
            $crate::git::submodule::git_submodule_deinit,
            // Git remote management commands
            $crate::git::remote::git_add_remote,
            $crate::git::remote::git_remove_remote,
            $crate::git::remote::git_set_remote_url,
            $crate::git::remote::git_set_remote_push_url,
            $crate::git::remote::git_rename_remote,
            // Git fetch/push/pull commands
            $crate::git::remote::git_fetch,
            $crate::git::remote::git_fetch_with_options,
            $crate::git::remote::git_push,
            $crate::git::remote::git_push_with_tags,
            $crate::git::remote::git_pull,
            $crate::git::remote::git_pull_rebase,
            $crate::git::remote::git_force_push_check,
            // Git tag commands
            $crate::git::tag::git_list_tags,
            $crate::git::tag::git_create_tag,
            $crate::git::tag::git_create_annotated_tag,
            $crate::git::tag::git_delete_tag,
            $crate::git::tag::git_push_tag,
            $crate::git::tag::git_delete_remote_tag,
            $crate::git::tag::git_checkout_tag,
            // Git worktree commands
            $crate::git::worktree::git_worktree_list,
            $crate::git::worktree::git_worktree_add,
            $crate::git::worktree::git_worktree_remove,
            $crate::git::worktree::git_worktree_lock,
            $crate::git::worktree::git_worktree_unlock,
            $crate::git::worktree::git_worktree_move,
            $crate::git::worktree::git_worktree_repair,
            $crate::git::worktree::git_worktree_prune,
            // Git LFS commands
            $crate::git::lfs::git_lfs_status,
            $crate::git::lfs::git_lfs_init,
            $crate::git::lfs::git_lfs_track,
            $crate::git::lfs::git_lfs_untrack,
            $crate::git::lfs::git_lfs_track_preview,
            $crate::git::lfs::git_lfs_fetch,
            $crate::git::lfs::git_lfs_pull,
            $crate::git::lfs::git_lfs_push,
            $crate::git::lfs::git_lfs_prune,
            $crate::git::lfs::git_lfs_lock,
            $crate::git::lfs::git_lfs_unlock,
            $crate::git::lfs::git_lfs_locks,
            $crate::git::lfs::git_lfs_file_info,
            $crate::git::lfs::git_lfs_dir_summary,
            // Git clone commands
            $crate::git::clone::git_clone,
            $crate::git::clone::git_clone_recursive,
            // Git merge commands
            $crate::git::merge::git_merge,
            $crate::git::merge::git_merge_abort,
            $crate::git::merge::git_merge_continue,
            // Git branch commands
            $crate::git::branch::git_publish_branch,
            $crate::git::branch::git_set_upstream,
            $crate::git::branch::git_branch_rename,
            $crate::git::branch::git_reset_soft,
            $crate::git::branch::git_clean,
            $crate::git::branch::git_checkout,
            $crate::git::branch::git_create_branch,
            $crate::git::branch::git_delete_branch,
            $crate::git::branch::git_reset,
            $crate::git::branch::git_revert,
            // Git repository watcher
            $crate::git::watcher::git_watch_repository,
            $crate::git::watcher::git_unwatch_repository,
            // Git line staging
            $crate::git::lines::git_stage_lines,
            $crate::git::lines::git_unstage_lines,
            // Git remote aliases
            $crate::git::remote::git_remote_add,
            $crate::git::remote::git_remote_remove,
            $crate::git::remote::git_remote_rename,
            // Git forge commands
            $crate::git::forge::git_forge_list_prs,
            $crate::git::forge::git_forge_get_pr,
            $crate::git::forge::git_forge_create_pr,
            $crate::git::forge::git_forge_merge_pr,
            $crate::git::forge::git_forge_pr_checks,
            $crate::git::forge::git_forge_get_pr_reviews,
            $crate::git::forge::git_forge_authenticate,
            // Git merge editor commands
            $crate::git::merge_editor::git_get_merge_conflicts,
            $crate::git::merge_editor::git_get_three_way_diff,
            $crate::git::merge_editor::git_resolve_conflict,
            $crate::git::merge_editor::git_abort_merge,
            // Additional git commands
            $crate::git::status::git_current_branch,
            $crate::git::status::git_remote_url,
            $crate::git::diff::git_diff_commit,
            $crate::git::diff::git_diff_structured,
            $crate::git::log::git_compare,
            $crate::git::branch::git_checkout_commit,
            $crate::git::tag::git_tag_diff,
        ])
    };
}
