#[macro_export]
macro_rules! misc_commands {
    (@commands $callback:ident [ $($acc:tt)* ]) => {
        $callback!([ $($acc)*
            // Startup lifecycle commands
            $crate::app::frontend_ready,
            // Server commands
            $crate::app::start_server,
            $crate::app::stop_server,
            $crate::app::get_server_info,
            $crate::app::get_logs,
            $crate::app::copy_logs_to_clipboard,
            $crate::app::get_version,
            $crate::app::open_in_browser,
            // Notification commands
            $crate::app::show_notification,
            // Auto-update commands
            $crate::auto_update::check_for_updates,
            $crate::auto_update::download_and_install_update,
            $crate::auto_update::get_update_status,
            $crate::auto_update::get_update_info,
            $crate::auto_update::dismiss_update,
            $crate::auto_update::restart_app,
            $crate::auto_update::get_app_version,
            $crate::auto_update::get_skipped_version,
            $crate::auto_update::set_skipped_version,
            // System specs commands
            $crate::system_specs::get_system_specs,
            $crate::system_specs::get_live_metrics,
            $crate::system_specs::start_live_metrics,
            $crate::system_specs::stop_live_metrics,
            $crate::system_specs::format_system_specs_for_clipboard,
            // Context server (MCP) commands
            $crate::context_server::commands::mcp_add_server,
            $crate::context_server::commands::mcp_remove_server,
            $crate::context_server::commands::mcp_list_servers,
            $crate::context_server::commands::mcp_get_server,
            $crate::context_server::commands::mcp_connect,
            $crate::context_server::commands::mcp_disconnect,
            $crate::context_server::commands::mcp_list_resources,
            $crate::context_server::commands::mcp_read_resource,
            $crate::context_server::commands::mcp_list_resource_templates,
            $crate::context_server::commands::mcp_list_tools,
            $crate::context_server::commands::mcp_call_tool,
            $crate::context_server::commands::mcp_list_prompts,
            $crate::context_server::commands::mcp_get_prompt,
            $crate::context_server::commands::mcp_query_context,
            $crate::context_server::commands::mcp_get_context_for_prompt,
            $crate::context_server::commands::mcp_ping,
            $crate::context_server::commands::mcp_set_log_level,
            // Activity Indicator commands
            $crate::activity::activity_create_task,
            $crate::activity::activity_update_task,
            $crate::activity::activity_complete_task,
            $crate::activity::activity_cancel_task,
            $crate::activity::activity_get_tasks,
            $crate::activity::activity_get_history,
            $crate::activity::activity_clear_history,
            $crate::activity::activity_get_task,
            $crate::activity::activity_set_progress,
            $crate::activity::activity_set_message,
            // Timeline / Local History commands
            $crate::timeline::timeline_init,
            $crate::timeline::timeline_get_entries,
            $crate::timeline::timeline_get_entry,
            $crate::timeline::timeline_create_snapshot,
            $crate::timeline::timeline_restore_snapshot,
            $crate::timeline::timeline_delete_entry,
            $crate::timeline::timeline_clear_file,
            $crate::timeline::timeline_clear_all,
            $crate::timeline::timeline_get_content,
            $crate::timeline::timeline_compare,
            $crate::timeline::timeline_set_label,
            $crate::timeline::timeline_get_stats,
            // Action Log commands
            $crate::action_log::action_log_entry,
            $crate::action_log::action_log_get_entries,
            $crate::action_log::action_log_track_file,
            $crate::action_log::action_log_record_edit,
            $crate::action_log::action_log_get_file_diff,
            $crate::action_log::action_log_get_tracked_files,
            $crate::action_log::action_log_accept_changes,
            $crate::action_log::action_log_reject_changes,
            $crate::action_log::action_log_untrack_file,
            $crate::action_log::action_log_clear_session,
            $crate::action_log::action_log_new_session,
            $crate::action_log::action_log_get_session,
            $crate::action_log::action_log_get_stats,
            $crate::action_log::action_log_set_config,
            $crate::action_log::action_log_get_config,
            // Diagnostics commands
            $crate::diagnostics::diagnostics_refresh,
            $crate::diagnostics::diagnostics_get_summary,
            $crate::diagnostics::diagnostics_get_by_file,
            $crate::diagnostics::diagnostics_get_for_file,
            $crate::diagnostics::diagnostics_filter,
            $crate::diagnostics::diagnostics_push_lsp,
            $crate::diagnostics::diagnostics_add_build,
            $crate::diagnostics::diagnostics_clear_build,
            $crate::diagnostics::write_file,
            // Rules Library commands
            $crate::rules_library::rules_scan_project,
            $crate::rules_library::rules_read_file,
            $crate::rules_library::rules_write_file,
            $crate::rules_library::rules_delete_file,
            $crate::rules_library::rules_create_file,
            $crate::rules_library::rules_get_user_dir,
            $crate::rules_library::rules_ensure_user_dir,
            $crate::rules_library::rules_watch_directory,
            $crate::rules_library::rules_unwatch_directory,
            $crate::rules_library::get_home_dir,
            $crate::rules_library::rules_save_file,
            // Prompt Store commands
            $crate::prompt_store::prompt_store_load,
            $crate::prompt_store::prompt_store_save,
            $crate::prompt_store::prompt_store_get,
            $crate::prompt_store::prompt_store_create,
            $crate::prompt_store::prompt_store_update,
            $crate::prompt_store::prompt_store_delete,
            $crate::prompt_store::prompt_store_export,
            $crate::prompt_store::prompt_store_import,
            $crate::prompt_store::prompt_store_get_path,
            // ACP Tools commands
            $crate::acp::commands::acp_list_tools,
            $crate::acp::commands::acp_get_tool,
            $crate::acp::commands::acp_get_tool_by_name,
            $crate::acp::commands::acp_search_tools,
            $crate::acp::commands::acp_register_tool,
            $crate::acp::commands::acp_unregister_tool,
            $crate::acp::commands::acp_update_tool,
            $crate::acp::commands::acp_execute_tool,
            $crate::acp::commands::acp_cancel_execution,
            $crate::acp::commands::acp_get_execution,
            $crate::acp::commands::acp_request_permission,
            $crate::acp::commands::acp_get_sandbox_config,
            $crate::acp::commands::acp_update_sandbox_config,
            $crate::acp::commands::acp_get_tools_for_ai,
            $crate::acp::commands::acp_handle_ai_tool_call,
            // Sandbox commands
            $crate::sandbox::commands::sandbox_spawn,
            $crate::sandbox::commands::sandbox_wait,
            $crate::sandbox::commands::sandbox_kill,
            $crate::sandbox::commands::sandbox_status,
            // MCP (Model Context Protocol) commands
            $crate::mcp::commands::mcp_get_status,
            $crate::mcp::commands::mcp_start,
            $crate::mcp::commands::mcp_stop,
            $crate::mcp::commands::mcp_get_config,
            // MCP Bridge commands (Node.js workspace tools server)
            $crate::mcp::commands::mcp_bridge_start,
            $crate::mcp::commands::mcp_bridge_stop,
            $crate::mcp::commands::mcp_bridge_list_tools,
            $crate::mcp::commands::mcp_bridge_call_tool,
            // Window management commands
            $crate::window::create_new_window,
            $crate::window::create_auxiliary_window,
            $crate::window::register_window_project,
            $crate::window::unregister_window,
            $crate::window::update_window_state,
            $crate::window::show_main_window,
            $crate::window::show_window,
            $crate::window::toggle_devtools,
            // WSL commands
            $crate::wsl::wsl_detect,
            $crate::wsl::wsl_connect,
            $crate::wsl::wsl_disconnect,
            $crate::wsl::wsl_execute,
            $crate::wsl::wsl_open_folder,
            $crate::wsl::wsl_open_terminal,
            $crate::wsl::wsl_get_shells,
            $crate::wsl::wsl_list_distributions,
            // Browser webview commands
            $crate::browser::browser_create,
            $crate::browser::browser_destroy,
            $crate::browser::browser_navigate,
            $crate::browser::browser_set_bounds,
            $crate::browser::browser_set_visible,
            $crate::browser::browser_list,
            $crate::browser::browser_get,
            $crate::browser::browser_focus,
            $crate::browser::browser_eval,
            $crate::browser::browser_back,
            $crate::browser::browser_forward,
            $crate::browser::browser_reload,
            // Process management commands
            $crate::process::terminate_cortex_process,
        ])
    };
}
