import { defineConfig } from "vitest/config";
import solid from "vite-plugin-solid";
import path from "path";

export default defineConfig({
  plugins: [
    solid({
      hot: false,
    }),
  ],

  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },

  test: {
    environment: "jsdom",
    setupFiles: ["./src/__tests__/setup.ts", "./src/test/setup.ts"],
    globals: true,
    allowOnly: false,
    passWithNoTests: false,
    include: [
      "src/**/*.{test,spec}.{ts,tsx}",
      "src/**/__tests__/**/*.{ts,tsx}",
    ],
    exclude: [
      "node_modules",
      "dist",
      "src-tauri",
      "mcp-server",
      "src/__tests__/setup.ts",
    ],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "json", "html"],
      reportsDirectory: "./coverage",
      exclude: [
        "node_modules/",
        "src/test/",
        "**/*.d.ts",
        "**/*.config.*",
        "**/types/**",
      ],
      include: [
        "src/components/Chat/TerminalBlock.tsx",
        "src/components/KeyboardShortcutsEditor.tsx",
        "src/components/KeyboardShortcutsEditorRow.tsx",
        "src/components/OutlineView.tsx",
        "src/components/QuickAccess.tsx",
        "src/components/accessibility/AccessibilitySettings.tsx",
        "src/components/accessibility/ScreenReaderAnnouncer.tsx",
        "src/components/accessibility/index.ts",
        "src/components/admin/SessionFilters.tsx",
        "src/components/admin/index.ts",
        "src/components/agents/AgentForm.tsx",
        "src/components/agents/index.ts",
        "src/components/ai/SupermavenStatus.tsx",
        "src/components/ai/index.ts",
        "src/components/ai/tools/index.ts",
        "src/components/codespaces/index.ts",
        "src/components/collab/index.ts",
        "src/components/comments/index.ts",
        "src/components/cortex/CortexAccountPanel.tsx",
        "src/components/cortex/CortexActivityBar.tsx",
        "src/components/cortex/CortexAgentsPanel.tsx",
        "src/components/cortex/CortexChatMessageBubble.tsx",
        "src/components/cortex/CortexChatPanel.tsx",
        "src/components/cortex/CortexCodeEditor.tsx",
        "src/components/cortex/CortexDebugPanel.tsx",
        "src/components/cortex/CortexDesktopLayout.tsx",
        "src/components/cortex/CortexDiffViewer.tsx",
        "src/components/cortex/CortexExtensionsPanel.tsx",
        "src/components/cortex/CortexFileExplorer.tsx",
        "src/components/cortex/CortexGitPanel.tsx",
        "src/components/cortex/CortexNotifications.tsx",
        "src/components/cortex/CortexPluginsPanel.tsx",
        "src/components/cortex/CortexSearchPanel.tsx",
        "src/components/cortex/CortexStatusBar.tsx",
        "src/components/cortex/CortexThemePicker.tsx",
        "src/components/cortex/CortexTitleBar.tsx",
        "src/components/cortex/CortexTokenLimitDisplay.tsx",
        "src/components/cortex/CortexUpdateFileView.tsx",
        "src/components/cortex/EditorBreadcrumbs.tsx",
        "src/components/cortex/command-palette/index.ts",
        "src/components/cortex/diagnostics/VulnerableDepsView.tsx",
        "src/components/cortex/diagnostics/index.ts",
        "src/components/cortex/dialogs/index.ts",
        "src/components/cortex/editor/index.ts",
        "src/components/cortex/explorer/ExplorerHeader.tsx",
        "src/components/cortex/explorer/ExplorerTreeView.tsx",
        "src/components/cortex/git/CIStatusBadge.tsx",
        "src/components/cortex/icons/figma-icon-map.ts",
        "src/components/cortex/icons/index.tsx",
        "src/components/cortex/index.ts",
        "src/components/cortex/layout/CortexIDELayout.tsx",
        "src/components/cortex/layout/CortexModeCarousel.tsx",
        "src/components/cortex/layout/CortexSidebarContainer.tsx",
        "src/components/cortex/layout/CortexVibeLayout.tsx",
        "src/components/cortex/layout/index.ts",
        "src/components/cortex/layout/types.tsx",
        "src/components/cortex/output/index.ts",
        "src/components/cortex/primitives/CortexButton.tsx",
        "src/components/cortex/primitives/CortexCodeNavHelp.tsx",
        "src/components/cortex/primitives/CortexConfigBadge.tsx",
        "src/components/cortex/primitives/CortexDropdown.tsx",
        "src/components/cortex/primitives/CortexDropdownItem.tsx",
        "src/components/cortex/primitives/CortexDropdownMenu.tsx",
        "src/components/cortex/primitives/CortexHeaderItem.tsx",
        "src/components/cortex/primitives/CortexIcon.tsx",
        "src/components/cortex/primitives/CortexIconButton.tsx",
        "src/components/cortex/primitives/CortexInput.tsx",
        "src/components/cortex/primitives/CortexModal.tsx",
        "src/components/cortex/primitives/CortexModelSelector.tsx",
        "src/components/cortex/primitives/CortexOpenProjectDropdown.tsx",
        "src/components/cortex/primitives/CortexSendButton.tsx",
        "src/components/cortex/primitives/CortexSeparator.tsx",
        "src/components/cortex/primitives/CortexSmallButton.tsx",
        "src/components/cortex/primitives/CortexStartPause.tsx",
        "src/components/cortex/primitives/CortexTabs.tsx",
        "src/components/cortex/primitives/CortexToggle.tsx",
        "src/components/cortex/primitives/CortexTooltip.tsx",
        "src/components/cortex/primitives/CortexTreeItem.tsx",
        "src/components/cortex/primitives/CortexVibeToggle.tsx",
        "src/components/cortex/primitives/index.ts",
        "src/components/cortex/titlebar/CortexLogo.tsx",
        "src/components/cortex/titlebar/MacWindowControls.tsx",
        "src/components/cortex/titlebar/TitleBarDropdownMenu.tsx",
        "src/components/cortex/titlebar/WindowControls.tsx",
        "src/components/cortex/titlebar/WindowsLinuxWindowControls.tsx",
        "src/components/cortex/titlebar/defaultMenus.ts",
        "src/components/cortex/titlebar/index.ts",
        "src/components/cortex/titlebar/platformDetect.ts",
        "src/components/cortex/vibe/AgentItem.tsx",
        "src/components/cortex/vibe/StreamingCursor.tsx",
        "src/components/cortex/vibe/VibeTabBar.tsx",
        "src/components/cortex/vibe/index.ts",
        "src/components/debug/BreakpointWidget.tsx",
        "src/components/debugger/BreakpointPanel.tsx",
        "src/components/debugger/CallStackPanel.tsx",
        "src/components/debugger/VariablesPanel.tsx",
        "src/components/debugger/index.ts",
        "src/components/dev/index.ts",
        "src/components/diagnostics/DiagnosticItem.tsx",
        "src/components/diagnostics/DiagnosticsFilter.tsx",
        "src/components/diagnostics/index.ts",
        "src/components/editor/BracketPairColorizer.tsx",
        "src/components/editor/BreadcrumbBar.tsx",
        "src/components/editor/Breadcrumbs.tsx",
        "src/components/editor/CodeActionPreviewDialog.tsx",
        "src/components/editor/EditorDecorations.tsx",
        "src/components/editor/EditorGrid.tsx",
        "src/components/editor/EditorInstanceContext.tsx",
        "src/components/editor/EditorMinimap.tsx",
        "src/components/editor/EditorSkeleton.tsx",
        "src/components/editor/FindReplaceWidget.tsx",
        "src/components/editor/GridSash.tsx",
        "src/components/editor/HexEditor.tsx",
        "src/components/editor/InlineDiff.tsx",
        "src/components/editor/Minimap.tsx",
        "src/components/editor/PeekView.tsx",
        "src/components/editor/RenameWidget.tsx",
        "src/components/editor/SnippetManager.tsx",
        "src/components/editor/StickyScroll.tsx",
        "src/components/editor/TabBar.tsx",
        "src/components/editor/breadcrumbs/BreadcrumbContextMenu.tsx",
        "src/components/editor/breadcrumbs/breadcrumbConstants.ts",
        "src/components/editor/breadcrumbs/breadcrumbHelpers.ts",
        "src/components/editor/breadcrumbs/breadcrumbTypes.ts",
        "src/components/editor/breadcrumbs/index.ts",
        "src/components/editor/core/index.ts",
        "src/components/editor/features/index.ts",
        "src/components/editor/grid/GridCellView.tsx",
        "src/components/editor/grid/MaximizeRestoreButton.tsx",
        "src/components/editor/grid/gridHelpers.ts",
        "src/components/editor/grid/index.ts",
        "src/components/editor/grid/types.ts",
        "src/components/editor/index.ts",
        "src/components/editor/modules/EditorTypes.ts",
        "src/components/editor/modules/index.ts",
        "src/components/extensions/ContributedPanel.tsx",
        "src/components/extensions/ContributedView.tsx",
        "src/components/extensions/index.ts",
        "src/components/git/CommitGraph.tsx",
        "src/components/git/index.ts",
        "src/components/index.ts",
        "src/components/keyboard/index.ts",
        "src/components/notebook/index.ts",
        "src/components/notebook/outputs/HtmlOutput.tsx",
        "src/components/notebook/outputs/MarkdownOutput.tsx",
        "src/components/notebook/outputs/TextOutput.tsx",
        "src/components/notebook/outputs/index.ts",
        "src/components/notifications/index.ts",
        "src/components/onboarding/index.ts",
        "src/components/output/OutputChannel.tsx",
        "src/components/output/OutputPanel.tsx",
        "src/components/output/index.ts",
        "src/components/preview/index.ts",
        "src/components/profiles/index.ts",
        "src/components/quickaccess/QuickAccessItem.tsx",
        "src/components/quickaccess/QuickAccessWidget.tsx",
        "src/components/quickaccess/index.ts",
        "src/components/remote/index.ts",
        "src/components/repl/index.ts",
        "src/components/session/index.ts",
        "src/components/settings/KeybindingsEditor.tsx",
        "src/components/settings/index.ts",
        "src/components/settings/keybindings/index.ts",
        "src/components/settings/keybindings/keybindingsHelpers.ts",
        "src/components/settings/keybindings/keybindingsModalStyles.ts",
        "src/components/settings/keybindings/keybindingsStyles.ts",
        "src/components/settings/keybindings/keybindingsTypes.ts",
        "src/components/share/PasswordPrompt.tsx",
        "src/components/share/ShareFooter.tsx",
        "src/components/share/index.ts",
        "src/components/snippets/index.ts",
        "src/components/tasks/index.ts",
        "src/components/terminal/index.ts",
        "src/components/testing/CoverageOverlay.tsx",
        "src/components/testing/TestOutput.tsx",
        "src/components/testing/TestResults.tsx",
        "src/components/testing/index.ts",
        "src/components/theme/ColorCustomizer.tsx",
        "src/components/theme/ThemePreview.tsx",
        "src/components/theme/index.ts",
        "src/components/timeline/TimelinePanel.tsx",
        "src/components/timeline/index.ts",
        "src/components/ui/AgentSkeleton.tsx",
        "src/components/ui/Avatar.tsx",
        "src/components/ui/Badge.tsx",
        "src/components/ui/Breadcrumb.tsx",
        "src/components/ui/Button.tsx",
        "src/components/ui/Card.tsx",
        "src/components/ui/Checkbox.tsx",
        "src/components/ui/ContextMenu.tsx",
        "src/components/ui/Divider.tsx",
        "src/components/ui/EmptyState.tsx",
        "src/components/ui/HomeSkeleton.tsx",
        "src/components/ui/Icon.tsx",
        "src/components/ui/IconButton.tsx",
        "src/components/ui/ListItem.tsx",
        "src/components/ui/LoadingSpinner.tsx",
        "src/components/ui/Modal.tsx",
        "src/components/ui/ProgressBar.tsx",
        "src/components/ui/Radio.tsx",
        "src/components/ui/SafeHTML.tsx",
        "src/components/ui/Select.tsx",
        "src/components/ui/SidebarSkeleton.tsx",
        "src/components/ui/Skeleton.tsx",
        "src/components/ui/Tabs.tsx",
        "src/components/ui/Text.tsx",
        "src/components/ui/Toggle.tsx",
        "src/components/ui/index.ts",
        "src/components/viewers/index.ts",
        "src/components/workbench/index.ts",
        "src/components/workspace-trust/RestrictedModeBadge.tsx",
        "src/components/workspace-trust/WorkspaceTrustEditor.tsx",
        "src/components/workspace-trust/index.ts",
        "src/components/workspace/WorkspaceManager.tsx",
        "src/components/workspace/WorkspaceTrustDialog.tsx",
        "src/context/EditorContext.tsx",
        "src/context/I18nContext.tsx",
        "src/context/IconThemeContext.tsx",
        "src/context/KeymapContext.tsx",
        "src/context/NotebookContext.tsx",
        "src/context/SessionContext.tsx",
        "src/context/ThemeContext.tsx",
        "src/context/debug/DebugDisassemblyContext.tsx",
        "src/context/debug/DebugProvider.tsx",
        "src/context/keymap/KeymapProvider.tsx",
        "src/context/theme/IconThemeProvider.tsx",
        "src/context/theme/ProductIconThemeProvider.tsx",
        "src/context/utils/ProviderComposer.tsx",
        "src/hooks/index.ts",
        "src/providers/index.ts",
        "src/providers/quickaccess/index.ts",
        "src/providers/quickaccess/types.ts",
        "src/sdk/client.ts",
        "src/sdk/errors.ts",
        "src/sdk/index.ts",
        "src/sdk/ipc.ts",
        "src/sdk/types.ts",
        "src/utils/ai/index.ts",
        "src/utils/ansiColors.ts",
        "src/utils/batchInvoke.ts",
        "src/utils/config.ts",
        "src/utils/criticalIcons.ts",
        "src/utils/decorators.ts",
        "src/utils/diffAlgorithm.ts",
        "src/utils/eventBus.ts",
        "src/utils/fileIcons.ts",
        "src/utils/findReplace.ts",
        "src/utils/format.ts",
        "src/utils/git/errors.ts",
        "src/utils/git/index.ts",
        "src/utils/git/providers/index.ts",
        "src/utils/git/registry.ts",
        "src/utils/git/types.ts",
        "src/utils/grid/index.ts",
        "src/utils/grid/layoutFactories.ts",
        "src/utils/grid/types.ts",
        "src/utils/gridSerializer.ts",
        "src/utils/iconCache.ts",
        "src/utils/iconMap.ts",
        "src/utils/index.ts",
        "src/utils/ipcCache.ts",
        "src/utils/json.ts",
        "src/utils/jsonc.ts",
        "src/utils/keybindingResolver.ts",
        "src/utils/lazyStyles.ts",
        "src/utils/lineOperations.ts",
        "src/utils/llm/index.ts",
        "src/utils/llm/types.ts",
        "src/utils/logger.ts",
        "src/utils/monaco-theme.ts",
        "src/utils/notifications.ts",
        "src/utils/provider-profiler.tsx",
        "src/utils/restrictedSettings.ts",
        "src/utils/retry.ts",
        "src/utils/searchUtils.ts",
        "src/utils/settingsMigration.ts",
        "src/utils/settingsValidation.ts",
        "src/utils/shellQuoting.ts",
        "src/utils/storage.ts",
        "src/utils/systemInfo.ts",
        "src/utils/telemetry/index.ts",
        "src/utils/theme-converter.ts",
        "src/utils/windowStorage.ts",
        "src/utils/workspace.ts"
      ],
      thresholds: {
        statements: 0,
        branches: 0,
        functions: 0,
        lines: 0,
      },
    },
    server: {
      deps: {
        inline: [
          "@solid-primitives",
        ],
      },
    },
    reporters: ["default"],
    testTimeout: 30000,
    isolate: true,
    watch: false,
    mockReset: true,
    restoreMocks: true,
    clearMocks: true,
  },
});