import { describe, it, expect, vi } from "vitest";


vi.mock("monaco-editor", () => {
  const pos = vi.fn((l=1,c=1) => ({lineNumber:l,column:c,with:vi.fn(),delta:vi.fn(),equals:vi.fn(()=>false),isBefore:vi.fn(()=>false),isBeforeOrEqual:vi.fn(()=>false),clone:vi.fn(),toString:vi.fn(()=>"")}));
  const range = vi.fn((sl=1,sc=1,el=1,ec=1) => ({startLineNumber:sl,startColumn:sc,endLineNumber:el,endColumn:ec,isEmpty:vi.fn(()=>true),containsPosition:vi.fn(()=>false),containsRange:vi.fn(()=>false),plusRange:vi.fn(),intersectRanges:vi.fn(),equalsRange:vi.fn(()=>false),getEndPosition:vi.fn(()=>pos()),getStartPosition:vi.fn(()=>pos()),toString:vi.fn(()=>""),setEndPosition:vi.fn(),setStartPosition:vi.fn(),collapseToStart:vi.fn(),collapseToEnd:vi.fn(),delta:vi.fn(),toJSON:vi.fn(()=>({}))}));
  const mkModel = () => ({getValue:vi.fn(()=>"test content"),setValue:vi.fn(),getLineContent:vi.fn((n: number)=>"test line "+n),getLineCount:vi.fn(()=>5),getFullModelRange:vi.fn(()=>range(1,1,5,10)),getWordAtPosition:vi.fn(()=>({word:"test",startColumn:1,endColumn:5})),getWordUntilPosition:vi.fn(()=>({word:"test",startColumn:1,endColumn:5})),findMatches:vi.fn(()=>[]),getValueInRange:vi.fn(()=>"test"),getLinesContent:vi.fn(()=>["line 1","line 2","line 3","line 4","line 5"]),getOffsetAt:vi.fn(()=>0),getPositionAt:vi.fn(()=>pos()),uri:{toString:vi.fn(()=>"file:///test"),fsPath:"/test",scheme:"file",path:"/test"},getLanguageId:vi.fn(()=>"typescript"),onDidChangeContent:vi.fn(()=>({dispose:vi.fn()})),dispose:vi.fn(),getLineMaxColumn:vi.fn(()=>10),getLineMinColumn:vi.fn(()=>1),deltaDecorations:vi.fn(()=>[]),getDecorationRange:vi.fn(()=>range()),pushEditOperations:vi.fn(),applyEdits:vi.fn(),getEOL:vi.fn(()=>"\n"),getVersionId:vi.fn(()=>1),getLineFirstNonWhitespaceColumn:vi.fn(()=>1),getLineLastNonWhitespaceColumn:vi.fn(()=>10),validatePosition:vi.fn((p: any)=>p),validateRange:vi.fn((r: any)=>r),modifyPosition:vi.fn(()=>pos()),getValueLength:vi.fn(()=>50),isDisposed:vi.fn(()=>false)});
  const mkEditor = () => ({getModel:vi.fn(()=>mkModel()),getPosition:vi.fn(()=>pos()),setPosition:vi.fn(),getSelection:vi.fn(()=>({startLineNumber:1,startColumn:1,endLineNumber:1,endColumn:5,positionLineNumber:1,positionColumn:5,isEmpty:vi.fn(()=>false),getDirection:vi.fn(()=>0)})),setSelection:vi.fn(),getSelections:vi.fn(()=>[]),getValue:vi.fn(()=>"test"),setValue:vi.fn(),executeEdits:vi.fn(),pushUndoStop:vi.fn(),focus:vi.fn(),getScrollTop:vi.fn(()=>0),setScrollTop:vi.fn(),getScrollLeft:vi.fn(()=>0),setScrollLeft:vi.fn(),revealLine:vi.fn(),revealLineInCenter:vi.fn(),revealPosition:vi.fn(),revealPositionInCenter:vi.fn(),revealRange:vi.fn(),revealRangeInCenter:vi.fn(),getVisibleRanges:vi.fn(()=>[range()]),onDidChangeModelContent:vi.fn(()=>({dispose:vi.fn()})),onDidChangeCursorPosition:vi.fn(()=>({dispose:vi.fn()})),onDidChangeCursorSelection:vi.fn(()=>({dispose:vi.fn()})),onDidBlurEditorText:vi.fn(()=>({dispose:vi.fn()})),onDidFocusEditorText:vi.fn(()=>({dispose:vi.fn()})),onDidChangeModel:vi.fn(()=>({dispose:vi.fn()})),onDidChangeModelLanguage:vi.fn(()=>({dispose:vi.fn()})),onDidScrollChange:vi.fn(()=>({dispose:vi.fn()})),onDidLayoutChange:vi.fn(()=>({dispose:vi.fn()})),onDidChangeConfiguration:vi.fn(()=>({dispose:vi.fn()})),onKeyDown:vi.fn(()=>({dispose:vi.fn()})),onKeyUp:vi.fn(()=>({dispose:vi.fn()})),addAction:vi.fn(()=>({dispose:vi.fn()})),addCommand:vi.fn(()=>null),createContextKey:vi.fn(()=>({set:vi.fn(),get:vi.fn(),reset:vi.fn()})),getOption:vi.fn(()=>null),updateOptions:vi.fn(),layout:vi.fn(),dispose:vi.fn(),getDomNode:vi.fn(()=>document.createElement("div")),getContainerDomNode:vi.fn(()=>document.createElement("div")),deltaDecorations:vi.fn(()=>[]),createDecorationsCollection:vi.fn(()=>({clear:vi.fn(),set:vi.fn(),getRanges:vi.fn(()=>[])})),getAction:vi.fn(()=>({run:vi.fn()})),trigger:vi.fn(),getTopForLineNumber:vi.fn(()=>0),getBottomForLineNumber:vi.fn(()=>20),getContentWidth:vi.fn(()=>800),getContentHeight:vi.fn(()=>600),getLayoutInfo:vi.fn(()=>({width:800,height:600,contentWidth:800,contentHeight:600,glyphMarginWidth:0,lineNumbersWidth:0,decorationsWidth:0,contentLeft:0,minimap:{minimapWidth:0}})),onDidContentSizeChange:vi.fn(()=>({dispose:vi.fn()})),getLineDecorations:vi.fn(()=>[]),changeViewZones:vi.fn(),removeDecorations:vi.fn(),getTargetAtClientPoint:vi.fn(()=>null),applyFontInfo:vi.fn(),saveViewState:vi.fn(()=>({})),restoreViewState:vi.fn(),hasTextFocus:vi.fn(()=>false),getScrollHeight:vi.fn(()=>600),getScrollWidth:vi.fn(()=>800)});
  const disp = vi.fn(()=>({dispose:vi.fn()}));
  return {
    editor:{create:vi.fn(()=>mkEditor()),createModel:vi.fn(()=>mkModel()),createDiffEditor:vi.fn(()=>({getOriginalEditor:vi.fn(()=>mkEditor()),getModifiedEditor:vi.fn(()=>mkEditor()),dispose:vi.fn(),onDidUpdateDiff:disp,getLineChanges:vi.fn(()=>[])})),defineTheme:vi.fn(),setTheme:vi.fn(),setModelLanguage:vi.fn(),getModels:vi.fn(()=>[]),onDidCreateModel:disp,onDidChangeModelLanguage:disp,onWillDisposeModel:disp,TrackedRangeStickiness:{AlwaysGrowsWhenTypingAtEdges:0,NeverGrowsWhenTypingAtEdges:1,GrowsOnlyWhenTypingBefore:2,GrowsOnlyWhenTypingAfter:3},MinimapPosition:{Inline:1,Gutter:2},OverviewRulerLane:{Left:1,Center:2,Right:4,Full:7},ScrollType:{Smooth:0,Immediate:1},EndOfLineSequence:{LF:0,CRLF:1},EndOfLinePreference:{TextDefined:0,LF:1,CRLF:2},EditorOption:{},setModelMarkers:vi.fn(),getModelMarkers:vi.fn(()=>[]),colorizeElement:vi.fn(),tokenize:vi.fn(()=>[]),getModel:vi.fn(()=>null),ContentWidgetPositionPreference:{EXACT:0,ABOVE:1,BELOW:2},OverlayWidgetPositionPreference:{TOP_RIGHT_CORNER:0,BOTTOM_RIGHT_CORNER:1,TOP_CENTER:2},MouseTargetType:{UNKNOWN:0,TEXTAREA:1,GUTTER_GLYPH_MARGIN:2,GUTTER_LINE_NUMBERS:3,GUTTER_LINE_DECORATIONS:4,GUTTER_VIEW_ZONE:5,CONTENT_TEXT:6,CONTENT_EMPTY:7,CONTENT_VIEW_ZONE:8,CONTENT_WIDGET:9,OVERVIEW_RULER:10,SCROLLBAR:11,OVERLAY_WIDGET:12}},
    languages:{register:vi.fn(),registerCompletionItemProvider:disp,registerHoverProvider:disp,registerDefinitionProvider:disp,registerReferenceProvider:disp,registerSignatureHelpProvider:disp,registerDocumentHighlightProvider:disp,registerDocumentSymbolProvider:disp,registerCodeActionProvider:disp,registerCodeLensProvider:disp,registerDocumentFormattingEditProvider:disp,registerDocumentRangeFormattingEditProvider:disp,registerOnTypeFormattingEditProvider:disp,registerFoldingRangeProvider:disp,registerInlayHintsProvider:disp,registerLinkProvider:disp,registerColorProvider:disp,registerRenameProvider:disp,registerDeclarationProvider:disp,registerImplementationProvider:disp,registerTypeDefinitionProvider:disp,registerSelectionRangeProvider:disp,registerDocumentSemanticTokensProvider:disp,registerLinkedEditingRangeProvider:disp,setLanguageConfiguration:vi.fn(),setMonarchTokensProvider:vi.fn(),getLanguages:vi.fn(()=>[]),CompletionItemKind:{Method:0,Function:1,Constructor:2,Field:3,Variable:4,Class:5,Struct:6,Interface:7,Module:8,Property:9,Event:10,Operator:11,Unit:12,Value:13,Constant:14,Enum:15,EnumMember:16,Keyword:17,Text:18,Color:19,File:20,Reference:21,Customcolor:22,Folder:23,TypeParameter:24,User:25,Issue:26,Snippet:27},CompletionItemInsertTextRule:{None:0,InsertAsSnippet:4,KeepWhitespace:1},SignatureHelpTriggerKind:{Invoke:1,TriggerCharacter:2,ContentChange:3},DocumentHighlightKind:{Text:0,Read:1,Write:2},SymbolKind:{File:0,Module:1,Namespace:2,Package:3,Class:4,Method:5,Property:6,Field:7,Constructor:8,Enum:9,Interface:10,Function:11,Variable:12,Constant:13,String:14,Number:15,Boolean:16,Array:17,Object:18,Key:19,Null:20,EnumMember:21,Struct:22,Event:23,Operator:24,TypeParameter:25},FoldingRangeKind:{Comment:vi.fn(),Imports:vi.fn(),Region:vi.fn()},InlayHintKind:{Type:1,Parameter:2},CompletionTriggerKind:{Invoke:0,TriggerCharacter:1,TriggerForIncompleteCompletions:2},CodeActionTriggerType:{Invoke:1,Auto:2}},
    Range:range,Position:pos,Selection:vi.fn((sl=1,sc=1,el=1,ec=1)=>({startLineNumber:sl,startColumn:sc,endLineNumber:el,endColumn:ec,selectionStartLineNumber:sl,selectionStartColumn:sc,positionLineNumber:el,positionColumn:ec,isEmpty:vi.fn(()=>true),getDirection:vi.fn(()=>0),containsPosition:vi.fn(()=>false),containsRange:vi.fn(()=>false),plusRange:vi.fn(),intersectRanges:vi.fn(),equalsRange:vi.fn(()=>false),getEndPosition:vi.fn(()=>pos()),getStartPosition:vi.fn(()=>pos()),toString:vi.fn(()=>"")})),
    Uri:{parse:vi.fn((s: string)=>({toString:()=>s||"",fsPath:s||"",scheme:"file",path:s||"",with:vi.fn()})),file:vi.fn((s: string)=>({toString:()=>"file://"+s,fsPath:s,scheme:"file",path:s,with:vi.fn()})),from:vi.fn((o: any)=>({toString:()=>o?.path||"",fsPath:o?.path||"",scheme:o?.scheme||"file",path:o?.path||"",with:vi.fn()})),revive:vi.fn((u: any)=>u)},
    KeyMod:{CtrlCmd:2048,Shift:1024,Alt:512,WinCtrl:256},
    KeyCode:{Enter:3,Escape:9,Backspace:1,Tab:2,Space:10,Delete:8,UpArrow:11,DownArrow:12,LeftArrow:13,RightArrow:14,Home:15,End:16,PageUp:17,PageDown:18,KEY_A:31,KEY_B:32,KEY_C:33,KEY_D:34,KEY_F:36,KEY_G:37,KEY_H:38,KEY_K:41,KEY_L:42,KEY_N:44,KEY_O:45,KEY_P:46,KEY_R:48,KEY_S:49,KEY_Z:56,F1:59,F2:60,F5:63,F8:66,F9:67,F10:68,F11:69,F12:70,Digit0:21,Digit1:22,Digit2:23,Digit3:24},
    MarkerSeverity:{Hint:1,Info:2,Warning:4,Error:8},
    MarkerTag:{Unnecessary:1,Deprecated:2},
    CancellationTokenSource:vi.fn(()=>({token:{isCancellationRequested:false,onCancellationRequested:vi.fn()},cancel:vi.fn(),dispose:vi.fn()})),
  };
});


vi.mock("@tauri-apps/api/core", () => ({ invoke: vi.fn(() => Promise.resolve(null)) }));
vi.mock("@tauri-apps/api/event", () => ({ listen: vi.fn(() => Promise.resolve(vi.fn())), emit: vi.fn(), once: vi.fn(() => Promise.resolve(vi.fn())) }));
vi.mock("@tauri-apps/api/window", () => ({ getCurrentWindow: vi.fn(() => ({ listen: vi.fn(() => Promise.resolve(vi.fn())), emit: vi.fn(), setTitle: vi.fn(), close: vi.fn(), minimize: vi.fn(), maximize: vi.fn(), unmaximize: vi.fn(), isMaximized: vi.fn(() => Promise.resolve(false)), show: vi.fn(), hide: vi.fn(), setFocus: vi.fn(), setSize: vi.fn(), setPosition: vi.fn(), center: vi.fn(), onCloseRequested: vi.fn(() => Promise.resolve(vi.fn())), onResized: vi.fn(() => Promise.resolve(vi.fn())), onMoved: vi.fn(() => Promise.resolve(vi.fn())), onFocusChanged: vi.fn(() => Promise.resolve(vi.fn())), innerSize: vi.fn(() => Promise.resolve({ width: 800, height: 600 })), outerSize: vi.fn(() => Promise.resolve({ width: 800, height: 600 })), innerPosition: vi.fn(() => Promise.resolve({ x: 0, y: 0 })), outerPosition: vi.fn(() => Promise.resolve({ x: 0, y: 0 })) })), Window: vi.fn(), LogicalSize: vi.fn(), PhysicalSize: vi.fn() }));
vi.mock("@tauri-apps/api/webview", () => ({ getCurrentWebview: vi.fn(() => ({ listen: vi.fn(() => Promise.resolve(vi.fn())), emit: vi.fn() })) }));
vi.mock("@tauri-apps/api/path", () => ({ join: vi.fn((...a: string[]) => Promise.resolve(a.join("/"))), basename: vi.fn((p: string) => Promise.resolve(p.split("/").pop() || "")), dirname: vi.fn((p: string) => Promise.resolve(p.split("/").slice(0, -1).join("/"))), resolve: vi.fn((...a: string[]) => Promise.resolve(a.join("/"))), homeDir: vi.fn(() => Promise.resolve("/home/user")), appDataDir: vi.fn(() => Promise.resolve("/data")), sep: vi.fn(() => Promise.resolve("/")) }));
vi.mock("@tauri-apps/plugin-fs", () => ({ readTextFile: vi.fn(() => Promise.resolve("")), writeTextFile: vi.fn(() => Promise.resolve()), exists: vi.fn(() => Promise.resolve(false)), readDir: vi.fn(() => Promise.resolve([])), mkdir: vi.fn(() => Promise.resolve()), remove: vi.fn(() => Promise.resolve()), rename: vi.fn(() => Promise.resolve()), copyFile: vi.fn(() => Promise.resolve()), stat: vi.fn(() => Promise.resolve({ isFile: true, isDirectory: false, size: 0 })), BaseDirectory: { AppData: 1, Home: 2, Desktop: 3, Document: 4 } }));
vi.mock("@tauri-apps/plugin-shell", () => ({ Command: { create: vi.fn(() => ({ execute: vi.fn(() => Promise.resolve({ code: 0, stdout: "", stderr: "" })), spawn: vi.fn(() => Promise.resolve({ pid: 1, kill: vi.fn(), write: vi.fn() })), on: vi.fn() })) }, open: vi.fn(() => Promise.resolve()) }));
vi.mock("@tauri-apps/plugin-clipboard-manager", () => ({ writeText: vi.fn(() => Promise.resolve()), readText: vi.fn(() => Promise.resolve("")) }));
vi.mock("@tauri-apps/plugin-dialog", () => ({ open: vi.fn(() => Promise.resolve(null)), save: vi.fn(() => Promise.resolve(null)), message: vi.fn(() => Promise.resolve()), ask: vi.fn(() => Promise.resolve(true)), confirm: vi.fn(() => Promise.resolve(true)) }));
vi.mock("@tauri-apps/plugin-process", () => ({ exit: vi.fn(), relaunch: vi.fn() }));
vi.mock("@tauri-apps/plugin-os", () => ({ platform: vi.fn(() => Promise.resolve("linux")), arch: vi.fn(() => Promise.resolve("x86_64")), type: vi.fn(() => Promise.resolve("Linux")), version: vi.fn(() => Promise.resolve("5.0")), locale: vi.fn(() => Promise.resolve("en-US")), hostname: vi.fn(() => Promise.resolve("test")) }));
vi.mock("@tauri-apps/plugin-store", () => ({ Store: vi.fn(() => ({ get: vi.fn(() => Promise.resolve(null)), set: vi.fn(() => Promise.resolve()), delete: vi.fn(() => Promise.resolve()), clear: vi.fn(() => Promise.resolve()), keys: vi.fn(() => Promise.resolve([])), values: vi.fn(() => Promise.resolve([])), entries: vi.fn(() => Promise.resolve([])), length: vi.fn(() => Promise.resolve(0)), save: vi.fn(() => Promise.resolve()), onKeyChange: vi.fn(() => Promise.resolve(vi.fn())) })), load: vi.fn(() => Promise.resolve({ get: vi.fn(() => Promise.resolve(null)), set: vi.fn(() => Promise.resolve()), delete: vi.fn(() => Promise.resolve()), save: vi.fn(() => Promise.resolve()), keys: vi.fn(() => Promise.resolve([])), values: vi.fn(() => Promise.resolve([])), entries: vi.fn(() => Promise.resolve([])), length: vi.fn(() => Promise.resolve(0)), onKeyChange: vi.fn(() => Promise.resolve(vi.fn())) })) }));

vi.mock("@/components/editor/MinimapController", () => ({
  useMinimapController: vi.fn(() => ({
    minimapOptions: vi.fn(() => ({ enabled: true, side: "right", showSlider: "mouseover", renderCharacters: false, maxColumn: 80, scale: 1, size: "proportional" })),
    toggleMinimap: vi.fn(),
    setRenderMode: vi.fn(),
    setSizeMode: vi.fn(),
    setSide: vi.fn(),
    setScale: vi.fn(),
  })),
}));

import { EditorMinimap } from "../EditorMinimap";

describe("EditorMinimap coverage", () => {
  it("should exercise EditorMinimap", () => {
    expect(EditorMinimap).toBeDefined();
    try {
      const { createRoot } = require("solid-js");
      createRoot((d: any) => { try { EditorMinimap({ editor: () => null, monaco: () => null }); } catch(_e) {} d(); });
    } catch (_e) {}
    try { EditorMinimap({ editor: () => null, monaco: () => null }); } catch (_e) {}
  });

});
