export * from "./client";
export * from "./errors";
export * from "./executor";
export * from "./types";
export * from "./safe-invoke";
export * from "./collab";
export * from "./diagnostics";
export * from "./git-graph";
export * from "./workspace-trust";
export * from "./scm-provider";
export * from "./workspace-symbols";
export { type CodeAction as LspCodeAction } from "./ipc";
export {
  type LspPosition,
  type LspRange,
  type CodeActionContext,
  type LspDiagnostic,
  type WorkspaceEdit,
  type TextEdit,
  type LspCommand,
  type CodeLens,
  type FormattingOptions,
  type PrepareRenameResult,
  type SignatureHelp,
  type SignatureInformation,
  type ParameterInformation,
  type InlayHint,
  type CallHierarchyItem,
  type CallHierarchyIncomingCall,
  type CallHierarchyOutgoingCall,
  type TypeHierarchyItem,
  type DapBreakpoint,
  type DapDataBreakpoint,
  type WatchExpression,
  type EvalResult,
  type DisassembledInstruction,
  type ExtensionInfo,
  type ExtensionPermissions,
  type ExtensionLifecycleState,
  type DiagnosticEntry,
  type DiagnosticsSummary,
  type DiagnosticsFilter,
  type TerminalSearchResult,
  type TerminalProfile,
  type TerminalLink,
  lspCodeAction,
  lspCodeLens,
  lspResolveCodeLens,
  lspFormatDocument,
  lspFormatRange,
  lspRename,
  lspPrepareRename,
  lspSignatureHelp,
  lspInlayHints,
  lspCallHierarchyPrepare,
  lspCallHierarchyIncoming,
  lspCallHierarchyOutgoing,
  lspTypeHierarchyPrepare,
  lspTypeHierarchySupertypes,
  lspTypeHierarchySubtypes,
  dapSetConditionalBreakpoint,
  dapSetLogpoint,
  dapSetDataBreakpoint,
  dapAddWatchExpression,
  dapRemoveWatchExpression,
  dapEvaluateWatch,
  dapDebugConsoleEval,
  dapDisassemble,
  extensionInstall,
  extensionUninstall,
  extensionEnable,
  extensionDisable,
  extensionGetPermissions,
  extensionSetPermissions,
  extensionGetLifecycleState,
  extensionTriggerHostFunction,
  extensionListInstalled,
  getDiagnosticsByFile,
  getDiagnosticsSummary,
  filterDiagnostics,
  searchTerminal,
  getTerminalProfiles,
  saveTerminalProfile,
  detectTerminalLinks,
  computeFoldingRanges,
  getWorkspaceSymbols,
  expandSnippet,
  computeInlineDiff,
  getBreadcrumbPath,
  getStickyScrollLines,
  type FoldingRange,
  type BreadcrumbSegment,
  type StickyScrollLineEntry,
  type InlineDiffLine,
  type InlineDiffCharChange,
  type InlineDiffResult,
  type ExpandedSnippet,
  type SnippetTabStop,
  type EditorSymbolEntry,
  type FileChange,
  type RenameResult,
  type ExtractResult,
  renameAcrossFiles,
  extractVariable,
  extractMethod,
} from "./ipc";
