export { ThemeProvider, useTheme, type Theme } from "./ThemeContext";
export { ModalActiveProvider, useModalActive, useModalActiveOptional } from "./ModalActiveContext";
export {
  AIProvider,
  useAI,
  type AIModel,
  type AIMessage,
  type Message as AIMessageRaw,
  type Thread as AIThread,
  type SubAgent,
  type StreamChunk,
  type ToolCall as AIToolCall,
  type ToolResult as AIToolResult,
  type ToolDefinition,
  type ToolParameter as AIToolParameter,
  type FileContext,
  type MessageContext,
  type AIContextValue,
} from "./AIContext";

// Provider composition utilities
export { 
  ProviderComposer, 
  createProviderGroup, 
  createDeferredProviderGroup,
} from "./utils/ProviderComposer";
export { 
  createLazyProvider, 
  createDeferredInitProvider,
} from "./utils/LazyProvider";

// Split editor contexts (for granular subscriptions)
export {
  EditorFilesProvider,
  useEditorFiles,
  type EditorFilesContextValue,
} from "./editor/EditorFilesContext";
export {
  EditorUIProvider,
  useEditorUI,
  type EditorUIContextValue,
} from "./editor/EditorUIContext";
export {
  EditorCursorProvider,
  useEditorCursor,
  type CursorInfo,
  type SelectionInfo,
  type EditorCursorContextValue,
} from "./editor/EditorCursorContext";
export {
  WorkspaceProvider,
  useWorkspace,
  FOLDER_COLORS,
  type WorkspaceFolder,
  type WorkspaceSettings,
  type WorkspaceFile,
  type WorkspaceContextValue,
} from "./WorkspaceContext";
export {
  FileOperationsProvider,
  useFileOperations,
  type FileOperation,
  type FileOperationData,
} from "./FileOperationsContext";
export { SDKProvider, useSDK, type Message, type Session, type ToolCall, type Config } from "./SDKContext";
export { SessionProvider, useSession } from "./SessionContext";
export { ToastProvider, useToast, type ToastVariant } from "./ToastContext";
export { PreviewProvider, usePreview, type PreviewServer } from "./PreviewContext";
export { VimProvider, useVim, type VimMode, type VimState, type VimContextValue } from "./VimContext";
export { CollabProvider, useCollab, type CollabUser, type CollabRoom, type CursorPosition, type SelectionRange } from "./CollabContext";
export {
  LSPProvider,
  useLSP,
  getLanguageId,
  getLanguageServerConfig,
  type Position,
  type Range,
  type Location,
  type Diagnostic,
  type DiagnosticSeverity,
  type ServerInfo,
  type ServerCapabilities,
  type CompletionItem,
  type CompletionResult,
  type HoverInfo,
  type DefinitionResult,
  type ReferencesResult,
  type LanguageServerConfig,
  type SemanticTokensLegend,
  type SemanticTokensResult,
  type DecodedSemanticToken,
} from "./LSPContext";
export {
  ExtensionsProvider,
  useExtensions,
  type Extension,
  type ExtensionManifest,
  type ExtensionContributes,
  type ThemeContribution,
  type LanguageContribution,
  type CommandContribution,
  type PanelContribution,
  type SettingsContribution,
  type MarketplaceExtension,
  type ExtensionTheme,
} from "./ExtensionsContext";
export {
  TasksProvider,
  useTasks,
  type TaskConfig,
  type TaskGroup,
  type TaskRun,
  type TaskHistory,
  type ProblemMatcher,
} from "./TasksContext";
export { LLMProvider, useLLM, type LLMContextValue, type UsageStats } from "./LLMContext";
export {
  RemoteProvider,
  useRemote,
  type AuthMethod,
  type PortForward,
  type ConnectionProfile,
  type RemoteFileEntry,
  type RemoteFileNode,
  type CommandResult,
  type ConnectionStatus,
  type ConnectionInfo,
} from "./RemoteContext";
export {
  SSHProvider,
  useSSH,
  type SSHContextValue,
} from "./SSHContext";
export {
  REPLProvider,
  useREPL,
  type KernelSpec,
  type KernelInfo,
  type Cell,
  type CellOutput,
  type KernelStatus,
  type CellStatus,
  type Variable,
} from "./REPLContext";
export {
  DebugProvider,
  useDebug,
  type DebugSessionConfig,
  type DebugSessionInfo,
  type DebugSessionState,
  type Thread,
  type StackFrame,
  type Source,
  type Variable as DebugVariable,
  type Breakpoint,
  type BreakpointLocation,
  type EvaluateResult,
  type OutputMessage,
  type WatchExpression,
} from "./DebugContext";

export {
  TelemetryProvider,
  useTelemetry,
  useTrackFeature,
  useTrackCommand,
  useTrackError,
  useTrackPerformance,
  useTrackRender,
  type TelemetryContextValue,
} from "./TelemetryContext";
export {
  ToolchainProvider,
  useToolchain,
  type ToolchainKind,
  type ToolchainInfo,
  type ProjectToolchains,
  type ToolchainDetectionResult,
} from "./ToolchainContext";
export {
  KeymapProvider,
  useKeymap,
  keyboardEventToKeystroke,
  type KeyModifiers,
  type Keystroke,
  type Keybinding,
  type CommandBinding,
  type KeybindingConflict,
  type KeymapState,
  type KeymapContextValue,
} from "./KeymapContext";
export {
  FormatterProvider,
  useFormatter,
  type FormatterType,
  type FormatRange,
  type FormatterOptions,
  type FormatRequest,
  type FormatResult,
  type ConfigInfo,
  type FormatterInfo,
  type FormatterSettings,
  type FormattingStatus,
  type FormatterContextValue,
} from "./FormatterContext";
export {
  SupermavenProvider,
  useSupermaven,
  type SupermavenContextValue,
  type SupermavenContextState,
} from "./SupermavenContext";
export {
  JournalProvider,
  useJournal,
  type HourFormat,
  type JournalEntry,
  type JournalTemplate,
  type JournalSettings,
} from "./JournalContext";
export {
  OutlineProvider,
  useOutline,
  type SymbolKind,
  type SymbolRange,
  type DocumentSymbol,
} from "./OutlineContext";
export {
  SnippetsProvider,
  useSnippets,
  type Snippet,
  type SnippetCollection,
  type SnippetFile,
  type SnippetPlaceholder,
  type ParsedSnippet,
  type ActiveSnippetSession,
} from "./SnippetsContext";
export {
  GitHostingProvider,
  useGitHosting,
} from "./GitHostingContext";
export {
  RecentProjectsProvider,
  useRecentProjects,
  type RecentProject,
} from "./RecentProjectsContext";
export {
  ChannelsProvider,
  useChannels,
  type Channel,
  type ChannelMember,
  type ChannelNote,
  type ChatMessage,
  type ChannelInvitation,
  type ChannelVisibility,
  type ChannelRole,
  type MemberStatus,
  type MessageAttachment,
} from "./ChannelsContext";
export {
  AutoUpdateProvider,
  useAutoUpdate,
  type AutoUpdateStatus,
  type AutoUpdateStatusType,
  type UpdateInfo,
  type UpdateAvailableData,
  type DownloadingData,
  type RestartRequiredData,
  type ErrorData,
} from "./AutoUpdateContext";
export {
  NotificationsProvider,
  useNotifications,
  type NotificationType,
  type NotificationPriority,
  type NotificationAction,
  type Notification,
  type NotificationFilter,
  type NotificationSettings,
} from "./NotificationsContext";
export {
  ContextServerProvider,
  useContextServer,
  PRESET_SERVERS,
  createServerConfig,
  type ServerType,
  type ServerStatus,
  type ServerCapabilities as McpServerCapabilities,
  type PromptsCapabilities,
  type ResourcesCapabilities,
  type ToolsCapabilities,
  type ContextServerConfig,
  type ContextServerInfo,
  type Resource,
  type ResourceContents,
  type ResourceTemplate,
  type Tool,
  type ToolAnnotations,
  type ToolResponseContentType,
  type CallToolResponse,
  type Prompt,
  type PromptArgument,
  type Role,
  type MessageContentType,
  type PromptMessage,
  type PromptsGetResponse,
  type LoggingLevel,
} from "./ContextServerContext";
export {
  TabSwitcherProvider,
  useTabSwitcher,
  type TabHistoryEntry,
} from "./TabSwitcherContext";
export {
  WhichKeyProvider,
  useWhichKey,
  type WhichKeySettings,
  type PendingSequence,
  type ContinuationBinding,
  type WhichKeyState,
  type WhichKeyContextValue,
} from "./WhichKeyContext";
export {
  ActivityIndicatorProvider,
  useActivityIndicator,
  useTask,
  type TaskPriority,
  type TaskStatus,
  type TaskSource,
  type ActivityTask,
  type TaskHistoryEntry,
  type CreateTaskOptions,
  type UpdateTaskOptions,
} from "./ActivityIndicatorContext";
export {
  InspectorProvider,
  useInspector,
  openInspector,
  toggleInspector,
  type ElementBounds,
  type ComputedStyle,
  type ElementProp,
  type ElementState,
  type PerformanceMetric,
  type InspectedElement,
  type ElementTreeNode,
} from "./InspectorContext";
export {
  DiagnosticsProvider,
  useDiagnostics,
  type DiagnosticSource,
  type DiagnosticPosition,
  type DiagnosticRange,
  type DiagnosticRelatedInfo,
  type CodeAction,
  type UnifiedDiagnostic,
  type FileDiagnostics,
  type GroupMode,
  type DiagnosticFilter,
  type DiagnosticCounts,
} from "./DiagnosticsContext";
export {
  PromptStoreProvider,
  usePromptStore,
  type SavedPrompt,
  type PromptCategory,
  type PromptExportData,
} from "./PromptStoreContext";
export {
  RulesLibraryProvider,
  useRulesLibrary,
  type Rule,
  type RuleSource,
  type RulesFile,
  type RuleInheritance,
  type RuleComposition,
  type RulePreview,
} from "./RulesLibraryContext";
export {
  LanguageSelectorProvider,
  useLanguageSelector,
  type LanguageInfo,
  type LanguageAssociation,
  type LanguageSelectorSettings,
} from "./LanguageSelectorContext";
export {
  ACPProvider,
  useACP,
  BUILTIN_TOOLS,
  createTool,
  validateToolArguments,
  type ToolPermission,
  type ToolExecutionStatus,
  type ToolParameter,
  type ToolInputSchema,
  type ToolAnnotations as ACPToolAnnotations,
  type ACPTool,
  type ToolExecutionRequest,
  type ToolResultContentType,
  type ToolExecutionResult,
  type ToolExecutionHistory,
  type ToolPermissionRequest,
  type ToolSandboxConfig,
} from "./ACPContext";
export {
  SettingsProvider,
  useSettings,
  useEditorSettings,
  useThemeSettings,
  useTerminalSettings,
  useAISettings,
  useSecuritySettings,
  useSearchSettings,
  useFilesSettings,
  useExplorerSettings,
  useZenModeSettings,
  useScreencastModeSettings,
  useDebugSettings,
  useGitSettings,
  useHttpSettings,
  useCommandPaletteSettings,
  DEFAULT_SETTINGS,
  DEFAULT_COMMAND_PALETTE,
  type EditorSettings,
  type ThemeSettings,
  type TerminalSettings,
  type AISettings,
  type SecuritySettings,
  type FilesSettings,
  type SearchSettings,
  type ExplorerSettings,
  type ZenModeSettings,
  type ScreencastModeSettings,
  type DebugSettings,
  type GitSettings,
  type HttpSettings,
  type CommandPaletteSettings,
  type ExtensionSettingsMap,
  type CortexSettings,
  type SemanticHighlightingSettings,
  type InlayHintsSettings,
  type CodeLensSettings,
  type SettingsState,
  type SettingsContextValue,
} from "./SettingsContext";
export {
  NotebookProvider,
  useNotebook,
  type CellType,
  type KernelStatus as NotebookKernelStatus,
  type KernelLanguage,
  type OutputType,
  type StreamName,
  type NotebookMetadata,
  type CellMetadata,
  type StreamOutput,
  type ExecuteResultOutput,
  type DisplayDataOutput,
  type ErrorOutput,
  type CellOutput as NotebookCellOutput,
  type NotebookCell,
  type JupyterNotebook,
  type NotebookData,
  type ExecutionQueueItem,
  type KernelInfo as NotebookKernelInfo,
} from "./NotebookContext";
export {
  TestingProvider,
  useTesting,
  type TestFramework,
  type TestFrameworkConfig,
  type TestStatus as TestingTestStatus,
  type TestItem,
  type TestRunResult,
  type TestRun,
  type CoverageData,
  type CoverageFileData,
  type TestFilter,
} from "./TestingContext";
export {
  LocalHistoryProvider,
  useLocalHistory,
  formatBytes,
  formatRelativeTime,
  formatFullTime,
  type HistoryEntry as LocalHistoryEntry,
  type HistoryTrigger,
  type LocalHistorySettings,
  type VersionComparison,
} from "./LocalHistoryContext";
export {
  AccessibilityProvider,
  useAccessibility,
  useAudioSignal,
  useAnnounce,
  useReducedMotion,
  useFontScale,
  type AudioSignalType,
  type FontScale,
  type FocusIndicatorStyle,
  type AccessibilityState,
  type AccessibilityContextValue,
} from "./AccessibilityContext";
export {
  SettingsSyncProvider,
  useSettingsSync,
  type SyncStatus,
  type SyncableItem,
  type SyncAccount,
  type SyncConflict,
  type ConflictResolution,
  type SyncItemConfig,
  type SyncItems,
  type SyncData,
  type SyncActivityEntry,
  type SettingsSyncState,
  type SettingsSyncContextValue,
} from "./SettingsSyncContext";
export {
  WebviewProvider,
  useWebview,
  buildCSPString,
  buildSandboxAttribute,
  wrapHtmlContent,
  type WebviewCSPConfig,
  type WebviewOptions,
  type WebviewMessage,
  type WebviewMessageHandler,
  type WebviewState,
  type WebviewData,
  type WebviewContextValue,
} from "./WebviewContext";
export {
  OutputProvider,
  useOutput,
  BUILTIN_CHANNELS,
  type OutputLine,
  type OutputChannel,
  type BuiltinChannelName,
  type CreateChannelOptions,
  type AppendLineOptions,
  type OutputContextValue,
} from "./OutputContext";
export {
  WindowsProvider,
  useWindows,
  useAuxiliaryWindowInfo,
  type AuxiliaryWindowType,
  type WindowPosition,
  type WindowSize,
  type WindowBounds,
  type AuxiliaryWindowOptions,
  type AuxiliaryWindow,
  type WindowStateUpdate,
  type WindowContentSync,
  type MergeWindowRequest,
  type WindowEventType,
  type WindowEvent,
} from "./WindowsContext";
export {
  MultiRepoProvider,
  useMultiRepo,
  type GitFileStatus,
  type GitConflictType,
  type GitFile,
  type GitBranch,
  type GitRemote,
  type GitStash,
  type RepoStatus,
  type RepositoryInfo,
  type MultiRepoState,
  type CrossRepoOperation,
  type MultiRepoContextValue,
} from "./MultiRepoContext";
export {
  WorkspaceTrustProvider,
  useWorkspaceTrust,
  useIsActionAllowed,
  useTrustStatus,
  type TrustLevel,
  type TrustedFolder,
  type RestrictedModeRestrictions,
  type TrustDecision,
  type WorkspaceTrustSettings,
  type WorkspaceTrustState,
  type WorkspaceTrustContextValue,
} from "./WorkspaceTrustContext";
export {
  SemanticSearchProvider,
  useSemanticSearch,
  type EmbeddingVector,
  type SemanticSearchResult,
  type IndexingStatus,
} from "./SemanticSearchContext";
export {
  SpeechProvider,
  useSpeech,
  type SpeechLanguage,
  type SpeechErrorType,
  type SpeechState,
  type SpeechContextValue,
} from "./SpeechContext";
export {
  CommentsProvider,
  useComments,
  type ReactionType,
  type CommentReaction,
  type CommentAuthor,
  type Comment,
  type CommentThread,
  type CommentLocation,
  type CommentFilter,
} from "./CommentsContext";
export {
  ChatEditingProvider,
  useChatEditing,
  type ChangeStatus,
  type FileChange,
  type EditingSession,
} from "./ChatEditingContext";
export {
  ProfilesProvider,
  useProfiles,
  useProfileQuickSwitch,
  type Profile,
  type ProfileMetadata,
  type ProfileUIState,
  type ProfileExportData,
  type ProfilesContextValue,
} from "./ProfilesContext";
export {
  IconThemeProvider,
  useIconTheme,
  BUILTIN_THEMES,
  type IconDefinition,
  type IconTheme,
  type IconThemeState,
  type IconThemeContextValue,
} from "./IconThemeContext";
export {
  AgentFollowProvider,
  useAgentFollow,
  createFileLocation,
  createTerminalLocation,
  createSearchLocation,
  createDirectoryLocation,
  type AgentLocation,
  type FollowConfig,
} from "./AgentFollowContext";
export {
  SubAgentProvider,
  useSubAgents,
  type SubAgent as CustomSubAgent,
  type SubAgentType,
  type SubAgentState,
  type SubAgentContextValue,
} from "./SubAgentContext";
export {
  BookmarksProvider,
  useBookmarks,
  type Bookmark,
} from "./BookmarksContext";
export {
  CodespacesProvider,
  useCodespaces,
  type Codespace,
  type CodespaceState,
  type CodespaceMachine,
  type CodespaceRepository,
  type CreateCodespaceOptions,
  type GitHubUser,
  type GitHubAuthState,
  type CodespacesSettings,
} from "./CodespacesContext";
export {
  QuickPickProvider,
  useQuickPick,
  type IQuickPick,
  type ShowQuickPickOptions,
} from "./QuickPickContext";
export {
  ActivityBarProvider,
  useActivityBar,
  useActivityBarOptional,
  ACTIVITY_BAR_DEFAULT_ITEMS,
  type ViewContainerId,
  type ViewId,
  type ActivityBarItemDefinition,
  type ActivityBarBadge,
  type ActivityBarState,
  type ActivityBarContextValue,
} from "./ActivityBarContext";
export {
  LayoutProvider,
  useLayout,
  useAuxiliaryBar,
  usePrimarySidebar,
  type ViewId as LayoutViewId,
  type ViewLocation,
  type SidebarPosition,
  type LayoutView,
  type AuxiliaryBarState,
  type PrimarySidebarState,
  type PanelState,
  type LayoutState,
  type LayoutContextValue,
} from "./LayoutContext";
export {
  QuickAccessProvider,
  useQuickAccess,
  type Disposable,
  type QuickPickItem as QuickAccessItem,
  type QuickAccessProvider as QuickAccessProviderType,
  type PinnedItem,
  type HistoryEntry as QuickAccessHistoryEntry,
  type QuickAccessContextValue,
} from "./QuickAccessContext";
export {
  EditorAssociationsProvider,
  useEditorAssociations,
  useEditorForFile,
  useAvailableEditorsForFile,
  BUILTIN_EDITORS,
  DEFAULT_ASSOCIATIONS,
  isCodeFile,
  isImageFile,
  isVideoFile,
  isAudioFile,
  isPdfFile,
  isNotebookFile,
  isMarkdownFile,
  matchesPattern,
  type EditorAssociation,
  type AvailableEditor,
  type Disposable as EditorDisposable,
  type EditorAssociationsContextValue,
} from "./EditorAssociationsContext";
export {
  ColorCustomizationsProvider,
  useColorCustomizations,
  COLOR_KEYS,
  colorKeyToCSSVar,
  isValidColor,
  type ColorValue,
  type ColorCustomization,
  type ThemeColorCustomizations,
  type ParsedColorCustomizations,
  type ColorKeyInfo,
  type ColorCustomizationsState,
  type ColorCustomizationsContextValue,
} from "./ColorCustomizationsContext";
export {
  TokenColorCustomizationsProvider,
  useTokenColorCustomizations,
  TOKEN_TYPES,
  TOKEN_SCOPE_MAP,
  type TokenFontStyle,
  type TokenColorSettings,
  type TextMateRule,
  type SimpleTokenCustomizations,
  type TokenColorCustomization,
  type ThemeTokenCustomizations,
  type ParsedTokenCustomizations,
  type TokenTypeInfo,
  type TokenColorCustomizationsState,
  type TokenColorCustomizationsContextValue,
} from "./TokenColorCustomizationsContext";
export {
  SemanticTokenCustomizationsProvider,
  useSemanticTokenCustomizations,
  SEMANTIC_TOKEN_TYPES,
  SEMANTIC_TOKEN_MODIFIERS,
  SEMANTIC_TOKEN_TYPE_INFO,
  SEMANTIC_TOKEN_MODIFIER_INFO,
  parseTokenSelector,
  buildTokenSelector,
  customizationsToMonacoRules,
  type SemanticTokenType,
  type SemanticTokenModifier,
  type SemanticTokenRule,
  type SemanticTokenRuleValue,
  type SemanticTokenCustomizations,
  type ThemeSemanticTokenCustomizations,
  type SemanticTokenTypeInfo,
  type SemanticTokenModifierInfo,
  type SemanticTokenCustomizationsContextValue,
} from "./SemanticTokenCustomizationsContext";
export {
  PolicySettingsProvider,
  usePolicySettings,
  useIsPolicyControlled,
  usePolicyValue,
  KNOWN_POLICY_KEYS,
  type PolicySource,
  type PolicySetting,
  type PolicyMetadata,
  type PolicySettingsState,
  type PolicySettingsContextValue,
} from "./PolicySettingsContext";
export {
  ExtensionBisectProvider,
  useExtensionBisect,
  useBisectStatus,
  type BisectState,
  type BisectPhase,
  type ExtensionBisectContextValue,
} from "./ExtensionBisectContext";
export {
  SearchProvider,
  useSearch,
  useSearchQuery,
  useSearchResults,
  useSearchOperations,
  useSearchHistory,
  useSearchEditors,
  useSearchProviders,
  DEFAULT_SEARCH_OPTIONS,
  DEFAULT_SEARCH_QUERY,
  type PatternType,
  type SearchQueryOptions,
  type SearchQuery,
  type SearchScope,
  type TextRange,
  type SearchMatch,
  type SearchResult,
  type SearchProgress,
  type SearchEditorState,
  type SearchHistoryEntry,
  type TextSearchProvider,
  type FileSearchProvider,
  type SearchStats,
  type SearchState,
  type SearchContextValue,
} from "./SearchContext";
export {
  ProductIconThemeProvider,
  useProductIconTheme,
  BUILT_IN_PRODUCT_ICON_THEMES,
  ALL_PRODUCT_ICON_IDS,
  PRODUCT_ICON_CATEGORIES,
  PRODUCT_ICON_CATEGORY_LABELS,
  type ProductIconCategory,
  type ProductIconId,
  type ProductIconDefinition,
  type ProductIconTheme,
} from "./ProductIconThemeContext";
export {
  CommandProvider,
  useCommands,
  type Command,
} from "./CommandContext";
export {
  EncodingProvider,
  useEncoding,
  getCategoryLabel,
  type EncodingInfo,
  type EncodingCategory,
} from "./EncodingContext";
export {
  ExtensionHostProvider,
  useExtensionHost,
  useExtension,
  useExtensionActive,
  useCommand as useExtensionHostCommand,
  useCommandHandler,
  useExtensionLogs,
  useExtensionEvent,
  useExtensionHostStats,
  useExtensionHostReady,
  createWorkspaceFolders,
  manifestToDescription,
  ExtensionStatus,
  LogLevel,
  ExtensionHostStatus,
  type ExtensionLogEntry,
  type ExtensionHostStats,
  type ExtensionHostOptions,
  type ExtensionHostAPI,
  type ExtensionHostProviderProps,
  type ExtensionDescription,
  type ExtensionRuntimeState,
  type ExtensionActivatedPayload,
  type ExtensionErrorPayload,
  type WorkspaceFolder as ExtensionWorkspaceFolder,
} from "./ExtensionHostContext";
export {
  NodeExtensionHostProvider,
  useNodeExtensionHost,
  type NodeHostStatus,
  type InstalledVscodeExtension,
  type NodeExtensionState,
  type ContributedStatusBarItem as NodeContributedStatusBarItem,
  type ContributedTreeView as NodeContributedTreeView,
  type ContributedWebviewPanel as NodeContributedWebviewPanel,
  type ContributedMenu as NodeContributedMenu,
  type NodeExtensionHostAPI,
} from "./NodeExtensionHostContext";
export {
  ExtensionRecommendationsProvider,
  useExtensionRecommendations,
  type ExtensionsJson,
  type ExtensionRecommendation,
  type ExtensionRecommendationsContextValue,
} from "./ExtensionRecommendationsContext";
export {
  QuickInputProvider,
  useQuickInput,
  ItemActivation,
  QuickPickItemButtonLocation,
  type QuickPickItem,
  type QuickPickSeparator,
  type QuickPickListItem,
  type ShowInputBoxOptions,
  type ShowQuickPickOptions as QuickInputShowQuickPickOptions,
  type QuickInputOptions,
  type QuickInputButton,
  type ValidationResult,
  type ValidationSeverity,
  type SelectionRange as QuickInputSelectionRange,
  type QuickTreeItem,
  type QuickNavigateConfiguration,
  type QuickPickSeparatorWithButtons,
  type QuickPickSeparatorButton,
  type QuickPickHighlights,
  type QuickInputExtendedOptions,
  type FlattenedTreeItem,
  type CheckboxState,
  type QuickTreeNodeEvent,
} from "./QuickInputContext";
export {
  TerminalsProvider,
  useTerminals,
  type TerminalInfo,
  type UpdateTerminalOptions,
  type CreateTerminalOptions,
  type TerminalProfileIcon,
  type TerminalProfile,
  type TerminalProfileConfig,
  type TerminalGroup,
  type TerminalSplitDirection,
  type CreateGroupOptions,
  type MoveToGroupOptions,
  type SSHConfig,
  type SSHTerminalInfo,
  type TerminalEnvironment,
  type TerminalQuickFix,
  type TerminalQuickFixAction,
  type TerminalPersistence,
  type ShellIntegrationState,
  type TerminalLink,
  type LinkDetectionOptions,
  type TerminalShellIntegrationState,
  type CommandHistoryEntry,
  type TerminalLinksState,
  type TerminalQuickFixState,
  type RecentCommandEntry,
  type PersistedTerminalState,
} from "./TerminalsContext";
export {
  NavigationHistoryProvider,
  useNavigationHistory,
  type NavigationLocation,
} from "./NavigationHistoryContext";
export {
  PlanProvider,
  usePlan,
} from "./PlanContext";
export {
  ViewModeProvider,
  useViewMode,
  type ViewMode,
} from "./ViewModeContext";
export {
  EditorProvider,
  useEditor,
  type CursorPosition as EditorCursorPosition,
  type Selection,
  type OpenFile,
  type SplitDirection,
  type EditorGroup,
  type EditorSplit,
  type EditorLayout,
  type GridCell,
  type EditorGridState,
} from "./EditorContext";

